language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - standard

# Ensure C++11 standard compiler is installed (required for node > v4)
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8